print('Welcome to the tip calculator!!!')
total=float(input('What was the total bill? $'))
percent=int(input('What percentage tip would you like to give? 10, 12, or 15? '))
person=int(input('How many people to split the bill? '))
tip=float((total*percent)/(100*person))
amount=tip+(total/person)
print('Each person should pay: $'+str(round(amount,2)))